server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 941267338220-nv42uhfak9jp8skr3ir76mpanub9g444.apps.googleusercontent.com
            client-secret: laJ5B9Vh9wLPr6LJR1KW6cPQ
          facebook:
            client-id: 289558572596393
            client-secret: c867e15bee706696f7fc6531a46a8983
